name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz libgraphviz-dev
          pip install --upgrade pip setuptools wheel
          pip install "tox<4.0.0"
          pip install .[dkg-construct]
      - name: Test with pytest
        run: |
          export MIRA_REST_URL=http://34.230.33.149:8771
          tox -e py
#      - name: Upload coverage report to codecov
#        uses: codecov/codecov-action@v1
#        if: success()
#        with:
#          file: coverage.xml
